### ISSUE TITLE
[BUG] IRCInit values

### ISSUE THREAD

**Issue by ChenBarPatensee** [cliquot22/TheiaMCR#1]
Hello, and thank you for writing this wonderful code for controlling the MCR unit.

I am using TL410P-R6 lens, and I think that the combination of 1000 steps + 1000 speed of controlling the IRC motor when running IRCInit() and afterwards IRCState(False) is damaging the IRC motor. The motor is not functioning well now, and I think that the default values on this functions have damaged it.

On another issue, when importing the code to MATLAB, it ignores "None" variables after initiation. That is, the MCRBoard is accessible after initiating the code, but focus, zoom and iris are not accessible, even after running focusInit, zoomInit and irisInit functions. I have solved it by initiating them to False value after initiation, so that MATLAB will recognize them, yet I think that a better solution is to initiate them to a motor class with an uninitiated state.

Thank you,
Chen Bar.

**Comment by cliquot22** [comment]
Thank you for the comments and evaluation of the software.  I would like to know more about what you are seeing.  
1. The default values for the IRC should be okay so there might be something else going on.  You can contact me at [mpeterson@theiatech.com](mailto://mpeterson@theiatech.com) and we can see if there is an issue with the lens.  
2. Can you provide a short snipet of code to show what you mean by initializing focus, zoom, iris to False?  The functions focusInit(vars), zoomInit(vars), and irisInit(vars) should create instances of the motor class which is required to move the motors.  Do you mean the focusInit() function should just instantiate a motor class and then you have to call an additional function to set the motor steps and home location?  

Mark

**Comment by ChenBarPatensee** [comment]
Thank you for responding me.
The lens is OK after restoring it to the values that we are used to work with them in the legacy software. But It didn't work well with the new Python code.

I am running the following code to initiate:
`obj.h = py.TheiaMCR.MCRControl("COM6");`
`obj.h.zoomInit(4073,1629);`
`obj.h.focusInit(9354,1122);`
`obj.h.irisInit(75);`
`obj.h.IRCInit();`

And when I open the legacy controller I get the following error:
![image](https://github.com/cliquot22/TheiaMCR/assets/143394199/e587bc24-0929-43e7-a842-07ec2942f77a)

And I get the following values in the configuration:
![image](https://github.com/cliquot22/TheiaMCR/assets/143394199/d89a787a-5afe-4797-9f10-328929606448)

After changing it to the following configuration, the lens is working well. I am not sure that these are the "right" values, but it is working...
![image](https://github.com/cliquot22/TheiaMCR/assets/143394199/dcc08cb8-9598-4ae4-890e-45e335e107e3)

------

About the other comment, when MATLAB is running the command:
`obj.h = py.TheiaMCR.MCRControl("COM6");`

it creates a class representing all the fields in the corresponding class. 

and by adding to:
`def __init__(self, com:str):`

the following code:
`        self.focus = None`
`        self.zoom = None`
`        self.iris = None`

it looks as:
![image](https://github.com/cliquot22/TheiaMCR/assets/143394199/f2de5c41-f63c-4c94-a3a7-40e658174458)

These are None values after connection, but when I am initiating to motor, it changes to the corresponding class type.

However, by running the original code without changing the init function, we get:
![image](https://github.com/cliquot22/TheiaMCR/assets/143394199/b7979e83-941d-4b6c-9fe1-beccb78f5c30)

and cannot control on the focus, zoom or iris classes, even after initiating them.
It is not a bug, rather than a feature to make the code easier to integrate into MATLAB.

Thank you,
Chen

**Comment by cliquot22** [comment]
Hi Chen
1. The values listed in the legacy application are treated as limits to any input.  So changing the zoom step limit to 3500 means that no input greater than 3500 can be entered.  However it doesn't prevent the user from entering 3500 twice.  

The input to the focusInit and zoomInit functions should be how many steps are physically available in the lens and the home position. But the parameters for focusInit and zoomInit are not correct.  They should be: 
```
obj.h.zoomInit(4037, 152)
obj.h.focusInit(9353, 8652)
```
I will add some notes to the readme file explaining where to find these number in the lens specifications (TL410 spec needs to be updated).  

Your original question was about the IRC.  In the legacy code it looks like the default 100ms is working for you.  But in the new code 1000ms is not working?  I haven't had a chance to check that yet.  Is this what you are seeing?  

----
2. Thank you for the suggestion about class initialization.  I will add that.  

Mark

**Comment by ChenBarPatensee** [comment]
Hello Mark,

About the IRC, I got the message error in the first image (Motor: 4, invalid max step value!) after the motor initiation with the new Python code and afterwards open the legacy interface, so is it possible that the values initiated by the Python code are invalid?
I think that the legacy program itself is giving the value 100ms after it sees invalid value.
Also, I am not sure about the velocity it gives to the camera, 1500 seems too high, the specs says maximal 1000 velocity, and we indeed hearing some clicks when we try to operate the lens with the configuration we get after running the Python code.

Thank you,
Chen.

**Comment by cliquot22** [comment]
Hi Chen,
I discovered the error.  The code never sets the maximum steps for the IRC motor so when using the legacy controller it assume 0 maybe.  I will adjust the TheiaMCR code to fix the max steps.  

For the motor velocities we recommend 1000pps (1200pps max).  For some reason the legacy code always changes the speed to the max speed when closing the configuration window.  This is a bug in the legacy code.  

Mark

**Comment by cliquot22** [comment]
v.2.1.11 is uploaded (and available on `pip install TheiaMCR`).  I adjusted how the IRC motor is initialized.  It doesn't create a motor instance because it only needs 2 states.  Let me know how this version works for you.  

Mark

**Comment by cliquot22** [comment]
Closed issue
